# Generated by Django 4.2.16 on 2024-10-29 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default='Ruffwal', max_length=256)),
                ('complaint', models.CharField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('resolution', models.CharField()),
                ('owner', models.CharField()),
                ('software', models.CharField(default='Ruffs', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField()),
                ('email', models.CharField()),
                ('phone_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField()),
            ],
        ),
    ]
